from .config import ConfigNode

CONFIG = ConfigNode()

CONFIG.VERSION = 2

CONFIG.MODEL = ConfigNode()
CONFIG.MODEL.LOAD_PROPOSALS = False
CONFIG.MODEL.MASK_ON = False
CONFIG.MODEL.KEYPOINT_ON = False
CONFIG.MODEL.DEVICE = "cuda"
CONFIG.MODEL.META_ARCHITECTURE = "GeneralizedRCNN"
CONFIG.MODEL.WEIGHTS = ""
CONFIG.MODEL.PIXEL_MEAN = [103.530, 116.280, 123.675]
CONFIG.MODEL.PIXEL_STD = [1.0, 1.0, 1.0]

# --------------------------------------------------------------------------------------------
CONFIG.INPUT = ConfigNode()
CONFIG.INPUT.MIN_SIZE_TRAIN = (800, )
CONFIG.INPUT.MIN_SIZE_TRAIN_SAMPLING = "choice"
CONFIG.INPUT.MAX_SIZE_TRAIN = 1333
CONFIG.INPUT.MIN_SIZE_TEST = 800
CONFIG.INPUT.MAX_SIZE_TEST = 1333
CONFIG.INPUT.RANDOM_FLIP = "horizontal"
CONFIG.INPUT.FORMAT = "BGR"
CONFIG.INPUT.MASK_FORMAT = "polygon"

CONFIG.INPUT.CROP = ConfigNode({"ENABLED": False})
CONFIG.INPUT.CROP.TYPE = "relative_range"
CONFIG.INPUT.CROP.SIZE = [0.9, 0.9]

# --------------------------------------------------------------------------------------------
CONFIG.DATASETS = ConfigNode()
CONFIG.DATASETS.TRAIN = ()
CONFIG.DATASETS.PROPOSAL_FILES_TRAIN = ()
CONFIG.DATASETS.PRECOMPUTED_PROPOSAL_TOP_K_TRAIN = 2000
CONFIG.DATASETS.TEST = ()
CONFIG.DATASETS.PROPOSAL_FILES_TEST = ()
CONFIG.DATASETS.PRECOMPUTED_PROPOSAL_TOP_K_TEST = 1000

# --------------------------------------------------------------------------------------------
CONFIG.DATALOADER = ConfigNode()
CONFIG.DATALOADER.NUM_WORKERS = 4
CONFIG.DATALOADER.ASPECT_RATIO_GROUPING = True
CONFIG.DATALOADER.SAMPLER_TRAIN = "TrainingSampLer"
CONFIG.DATALOADER.REPEAT_THRESHOLD = 0.0
CONFIG.DATALOADER.FILTER_EMPTY_ANNOTATIONS = True

# --------------------------------------------------------------------------------------------
CONFIG.MODEL.BACKBONE = ConfigNode()
CONFIG.MODEL.BACKBONE.NAME = "build_resnet_backbone"
CONFIG.MODEL.BACKBONE.FREEZE_AT = 2

# --------------------------------------------------------------------------------------------
CONFIG.MODEL.FPN = ConfigNode()
CONFIG.MODEL.FPN.IN_FEATURES = []
CONFIG.MODEL.FPN.OUT_CHANNELS = 256
CONFIG.MODEL.FPN.NORM = ""
CONFIG.MODEL.FPN.FUSE_TYPE = "sum"

# --------------------------------------------------------------------------------------------
CONFIG.MODEL.PROPOSAL_GENERATOR = ConfigNode()
CONFIG.MODEL.PROPOSAL_GENERATOR.NAME = "RPN"
CONFIG.MODEL.PROPOSAL_GENERATOR.MIN_SIZE = 0

# --------------------------------------------------------------------------------------------
CONFIG.MODEL.ANCHOR_GENERATOR = ConfigNode()
CONFIG.MODEL.ANCHOR_GENERATOR.NAME = "DefaultAnchorGenerator"
CONFIG.MODEL.ANCHOR_GENERATOR.SIZES = [[32, 64, 128, 256, 512]]
CONFIG.MODEL.ANCHOR_GENERATOR.ASPECT_RATIOS = [[0.5, 1.0, 2.0]]
CONFIG.MODEL.ANCHOR_GENERATOR.ANGLES = [[-90, 0, 90]]
CONFIG.MODEL.ANCHOR_GENERATOR.OFFSET = 0.0

# --------------------------------------------------------------------------------------------
CONFIG.MODEL.RPN = ConfigNode()
CONFIG.MODEL.RPN.HEAD_NAME = "StandardRPNHead"
CONFIG.MODEL.RPN.IN_FEATURES = ["res4"]
CONFIG.MODEL.RPN.BOUNDARY_THRESH = -1
CONFIG.MODEL.RPN.IOU_THRESHOLDS = [0.3, 0.7]
CONFIG.MODEL.RPN.IOU_LABELS = [0, -1, 1]
CONFIG.MODEL.RPN.BATCH_SIZE_PER_IMAGE = 256
CONFIG.MODEL.RPN.POSITIVE_FRACTION = 0.5
CONFIG.MODEL.RPN.BOUNDING_BOX_REG_LOSS_TYPE = "smooth_l1"
CONFIG.MODEL.RPN.BOUNDING_BOX_REG_LOSS_WEIGHT = 1.0
CONFIG.MODEL.RPN.BOUNDING_BOX_REG_WEIGHTS = (1.0, 1.0, 1.0, 1.0)
CONFIG.MODEL.RPN.SMOOTH_L1_BETA = 0.0
CONFIG.MODEL.RPN.LOSS_WEIGHT = 1.0
CONFIG.MODEL.RPN.PRE_NMS_TOP_K_TRAIN = 12000
CONFIG.MODEL.RPN.PRE_NMS_TOP_K_TEST = 6000
CONFIG.MODEL.RPN.POST_NMS_TOP_K_TRAIN = 2000
CONFIG.MODEL.RPN.POST_NMS_TOP_K_TEST = 1000
CONFIG.MODEL.RPN.NMS_THRESH = 0.7

# --------------------------------------------------------------------------------------------
CONFIG.MODEL.ROI_HEADS = ConfigNode()
CONFIG.MODEL.ROI_HEADS.NAME = "Res5ROIHeads"
CONFIG.MODEL.ROI_HEADS.NUM_CLASSES = 80
CONFIG.MODEL.ROI_HEADS.IN_FEATURES = ["res4"]
CONFIG.MODEL.ROI_HEADS.IOU_THRESHOLDS = [0.5]
CONFIG.MODEL.ROI_HEADS.IOU_LABELS = [0, 1]
CONFIG.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 512
CONFIG.MODEL.ROI_HEADS.POSITIVE_FRACTION = 0.25
CONFIG.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.05
CONFIG.MODEL.ROI_HEADS.NMS_THRESH_TEST = 0.5
CONFIG.MODEL.ROI_HEADS.PROPOSAL_APPEND_GT = True

# --------------------------------------------------------------------------------------------
CONFIG.MODEL.ROI_BOX_HEAD = ConfigNode()
CONFIG.MODEL.ROI_BOX_HEAD.NAME = ""
CONFIG.MODEL.ROI_BOX_HEAD.BOUNDING_BOX_REG_LOSS_TYPE = "smooth_l1"
CONFIG.MODEL.ROI_BOX_HEAD.BOUNDING_BOX_REG_LOSS_WEIGHT = 1.0
CONFIG.MODEL.ROI_BOX_HEAD.BOUNDING_BOX_REG_WEIGHTS = (10.0, 10.0, 5.0, 5.0)
CONFIG.MODEL.ROI_BOX_HEAD.SMOOTH_L1_BETA = 0.0
CONFIG.MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION = 14
CONFIG.MODEL.ROI_BOX_HEAD.POOLER_SAMPLING_RATIO = 0
CONFIG.MODEL.ROI_BOX_HEAD.POOLER_TYPE = "ROIAlignV2"
CONFIG.MODEL.ROI_BOX_HEAD.NUM_FC = 0
CONFIG.MODEL.ROI_BOX_HEAD.FC_DIM = 1024
CONFIG.MODEL.ROI_BOX_HEAD.CONV_DIM = 256
CONFIG.MODEL.ROI_BOX_HEAD.NORM = ""
CONFIG.MODEL.ROI_BOX_HEAD.CLASS_AGNOSTIC_BOUNDING_BOX_REG = False
CONFIG.MODEL.ROI_BOX_HEAD.TRAIN_ON_PREDICT_BOXES = False

# --------------------------------------------------------------------------------------------
CONFIG.MODEL.ROI_BOX_CASCADE_HEAD = ConfigNode()
CONFIG.MODEL.ROI_BOX_CASCADE_HEAD.BOUNDING_BOX_REG_WEIGHTS = (
    (10.0, 10.0, 5.0, 5.0),
    (20.0, 20.0, 10.0, 10.0),
    (30.0, 30.0, 15.0, 15.0)
)
CONFIG.MODEL.ROI_BOX_CASCADE_HEAD.IOUS = (0.5, 0.6, 0.7)

# --------------------------------------------------------------------------------------------
CONFIG.MODEL.ROI_MASK_HEAD = ConfigNode()
CONFIG.MODEL.ROI_MASK_HEAD.NAME = "MaskRCNNConvUpSampleHead"
CONFIG.MODEL.ROI_MASK_HEAD.POOLER_RESOLUTION = 14
CONFIG.MODEL.ROI_MASK_HEAD.POOLER_SAMPLING_RATIO = 0
CONFIG.MODEL.ROI_MASK_HEAD.NUM_CONV = 0
CONFIG.MODEL.ROI_MASK_HEAD.CONV_DIM = 256
CONFIG.MODEL.ROI_MASK_HEAD.NORM = ""
CONFIG.MODEL.ROI_MASK_HEAD.CLASS_AGNOSTIC_MASK = False
CONFIG.MODEL.ROI_MASK_HEAD.POLLER_TYPE = "ROIAlignV2"

# --------------------------------------------------------------------------------------------
CONFIG.MODEL.ROI_KEYPOINT_HEAD = ConfigNode()
CONFIG.MODEL.ROI_KEYPOINT_HEAD.NAME = "KRCNNConvDeConvUpSampleHead"
CONFIG.MODEL.ROI_KEYPOINT_HEAD.POOLER_RESOLUTION = 14
CONFIG.MODEL.ROI_KEYPOINT_HEAD.POOLER_SAMPLING_RATIO = 0
CONFIG.MODEL.ROI_KEYPOINT_HEAD.CONV_DIMS = tuple(512 for _ in range(8))
CONFIG.MODEL.ROI_KEYPOINT_HEAD.NUM_KEYPOINTS = 17  # Get 17 from COCO datasets.
CONFIG.MODEL.ROI_KEYPOINT_HEAD.MIN_KEYPOINTS_PER_IMAGE = 1
CONFIG.MODEL.ROI_KEYPOINT_HEAD.NORMALIZE_LOSS_BY_VISIBLE_KEYPOINTS = True
CONFIG.MODEL.ROI_KEYPOINT_HEAD.LOSS_WEIGHT = 1.0
CONFIG.MODEL.ROI_KEYPOINT_HEAD.POOLER_TYPE = "ROIAlignV2"

# --------------------------------------------------------------------------------------------
CONFIG.MODEL.SEMANTIC_SEGMENTATION_HEAD = ConfigNode()
CONFIG.MODEL.SEMANTIC_SEGMENTATION_HEAD.NAME = "SemanticSegmentationFPNHead"
CONFIG.MODEL.SEMANTIC_SEGMENTATION_HEAD.IN_FEATURES = ["P2", "P3", "P4", "P5"]
CONFIG.MODEL.SEMANTIC_SEGMENTATION_HEAD.IGNORE_VALUE = 255
CONFIG.MODEL.SEMANTIC_SEGMENTATION_HEAD.NUM_CLASSES = 54
CONFIG.MODEL.SEMANTIC_SEGMENTATION_HEAD.CONVS_DIM = 128
CONFIG.MODEL.SEMANTIC_SEGMENTATION_HEAD.COMMON_STRIDE = 4
CONFIG.MODEL.SEMANTIC_SEGMENTATION_HEAD.NORM = "GN"
CONFIG.MODEL.SEMANTIC_SEGMENTATION_HEAD.LOSS_WEIGHT = 1.0

# --------------------------------------------------------------------------------------------
CONFIG.MODEL.PANOPTIC_FPN = ConfigNode()
CONFIG.MODEL.PANOPTIC_FPN.INSTANCE_LOSS_WEIGHT = 1.0

CONFIG.MODEL.PANOPTIC_FPN.COMBINE = ConfigNode({"ENABLED": True})
CONFIG.MODEL.PANOPTIC_FPN.COMBINE.OVERLAP_THRESH = 0.5
CONFIG.MODEL.PANOPTIC_FPN.COMBINE.STUFF_AREA_LIMIT = 4096
CONFIG.MODEL.PANOPTIC_FPN.COMBINE.INSTANCES_CONFIDENCE_THRESH = 0.5

# --------------------------------------------------------------------------------------------
CONFIG.MODEL.RETINANET = ConfigNode()
CONFIG.MODEL.RETINANET.NUM_CLASSES = 80
CONFIG.MODEL.RETINANET.IN_FEATURES = ["P3", "P4", "P5", "P6", "P7"]
CONFIG.MODEL.RETINANET.NUM_CONVS = 4
CONFIG.MODEL.RETINANET.IOU_THRESHOLDS = [0.4, 0.5]
CONFIG.MODEL.RETINANET.IOU_LABELS = [0, -1, 1]
CONFIG.MODEL.RETINANET.PRIOR_PROB = 0.01
CONFIG.MODEL.RETINANET.SCORE_THRESH_TEST = 0.05
CONFIG.MODEL.RETINANET.TOP_K_CANDIDATES_TEST = 1000
CONFIG.MODEL.RETINANET.NMS_THRESH_TEST = 0.5
CONFIG.MODEL.RETINANET.BOUNDING_BOX_REG_WEIGHTS = (1.0, 1.0, 1.0, 1.0)
CONFIG.MODEL.RETINANET.FOCAL_LOSS_GAMMA = 2.0
CONFIG.MODEL.RETINANET.FOCAL_LOSS_ALPHA = 0.25
CONFIG.MODEL.RETINANET.SMOOTH_L1_LOSS_BETA = 0.1
CONFIG.MODEL.RETINANET.BOUNDING_BOX_REG_LOSS_TYPE = "smooth_l1"
CONFIG.MODEL.RETINANET.NORM = ""

# --------------------------------------------------------------------------------------------
CONFIG.MODEL.RESNETS = ConfigNode()
CONFIG.MODEL.RESNETS.DEPTH = 50
CONFIG.MODEL.RESNETS.OUT_FEATURES = ["res4"]
CONFIG.MODEL.RESNETS.NUM_GROUPS = 1
CONFIG.MODEL.RESNETS.NORM = "FrozenBatchNorm"
CONFIG.MODEL.RESNETS.WIDTH_PER_GROUP = 64
CONFIG.MODEL.RESNETS.STRIDE_IN_1X1 = True
CONFIG.MODEL.RESNETS.RES5_DILATION = 1
CONFIG.MODEL.RESNETS.DEFORM_ON_PER_STAGE = [False, False, False, False]
CONFIG.MODEL.RESNETS.DEFORM_MODULATED = False
CONFIG.MODEL.RESNETS.DEFORM_NUM_GROUPS = 1

# --------------------------------------------------------------------------------------------
CONFIG.SOLVER = ConfigNode()
CONFIG.SOLVER.LR_SCHEDULER_NAME = "WarmupMultistepLR"
CONFIG.SOLVER.MAX_ITER = 40000
CONFIG.SOLVER.BASE_LR = 0.001
CONFIG.SOLVER.MOMENTUM = 0.9
CONFIG.SOLVER.NESTEROV = False
CONFIG.SOLVER.WEIGHT_DECAY = 0.0001
CONFIG.SOLVER.WEIGHT_DECAY_NORM = 0.0
CONFIG.SOLVER.GAMMA = 0.1
CONFIG.SOLVER.STEPS = (30000, )
CONFIG.SOLVER.WARMUP_FACTOR = 1.0 / 1000
CONFIG.SOLVER.WARMUP_ITERS = 1000
CONFIG.SOLVER.WARMUP_METHOD = "linear"
CONFIG.SOLVER.CHECKPOINT_PERIOD = 5000
CONFIG.SOLVER.IMAGES_PER_BATCH = 16
CONFIG.SOLVER.REFERENCE_WORLD_SIZE = 0
CONFIG.SOLVER.BIAS_LR_FACTOR = 1.0
CONFIG.SOLVER.WEIGHT_DECAY_BIAS = CONFIG.SOLVER.WEIGHT_DECAY

CONFIG.SOLVER.CLIP_GRADIENTS = ConfigNode({"ENABLED": False})
CONFIG.SOLVER.CLIP_GRADIENTS.CLIP_TYPE = "value"
CONFIG.SOLVER.CLIP_GRADIENTS.CLIP_VALUE = 1.0
CONFIG.SOLVER.CLIP_GRADIENTS.NORM_TYPE = 2.0

# --------------------------------------------------------------------------------------------
CONFIG.TEST = ConfigNode()
CONFIG.TEST.EXPECTED_RESULTS = []
CONFIG.TEST.EVAL_PERIOD = 0
CONFIG.TEST.KEYPOINT_OKS_SIGMAS = []  # OKS is an "Object Keypoint Similarity"
CONFIG.TEST.DETECTIONS_PER_IMAGE = 100

CONFIG.TEST.AUG = ConfigNode({"ENABLED": False})
CONFIG.TEST.AUG.MIN_SIZES = (400, 500, 600, 700, 800, 900, 1000, 1100, 1200)
CONFIG.TEST.AUG.MAX_SIZE = 4000
CONFIG.TEST.AUG.FLIP = True

CONFIG.TEST.PRECISE_BATCH_NORM = ConfigNode({"ENABLED": False})
CONFIG.TEST.PRECISE_BATCH_NORM.NUM_ITER = 200

# --------------------------------------------------------------------------------------------
CONFIG.OWOD = ConfigNode()
CONFIG.OWOD.ENABLE_THRESHOLD_AUTOLABEL_UNKNOWN = False
CONFIG.OWOD.NUM_UNKNOWN_PER_IMAGE = 1
CONFIG.OWOD.ENABLE_UNCERTAIN_AUTOLABEL_UNKNOWN = False
CONFIG.OWOD.ENABLE_CLUSTERING = False
CONFIG.OWOD.PREVIOUS_INTRODUCED_CLASS = 0
CONFIG.OWOD.CURRENT_INTRODUCED_CLASS = 20
CONFIG.OWOD.COMPUTE_ENERGY = False
CONFIG.OWOD.ENERGY_SAVE_PATH = ""
CONFIG.OWOD.SKIP_TRAINING_WHILE_EVAL = False
CONFIG.OWOD.FEATURE_STORE_SAVE_PATH = ""
CONFIG.OWOD.TEMPERATURE = 1.5

CONFIG.OWOD.CLUSTERING = ConfigNode()
CONFIG.OWOD.CLUSTERING.ITEMS_PER_CLASS = 10
CONFIG.OWOD.CLUSTERING.START_ITER = 100
CONFIG.OWOD.CLUSTERING.UPDATE_MU_ITER = 200  # MU IS 'μ'
CONFIG.OWOD.CLUSTERING.MOMENTUM = 0.9
CONFIG.OWOD.CLUSTERING.Z_DIMENSION = 64
CONFIG.OWOD.CLUSTERING.MARGIN = 10.0

# --------------------------------------------------------------------------------------------
CONFIG.OUTPUT_DIR = "./output"
CONFIG.SEED = -1
CONFIG.CUDNN_BENCHMARK = False
CONFIG.VIS_PERIOD = 0

CONFIG.GLOBAL = ConfigNode()
CONFIG.GLOBAL.HACK = 1.0
